### ISSUE TITLE
Problem installing BagIt plugin with Omeka 2.2.2

### ISSUE THREAD

**Issue by ccronje** [scholarslab/BagItPlugin#5]
The BagIt download (http://omeka.org/wordpress/wp-content/uploads/BagIt-2.0.0.zip) does not contain expected files (see error below) - are there any workarounds please?

Warning: require_once(/var/www/html/omeka-2.2.2/plugins/BagIt/models/Table/Table_BagitFileCollection.php) [function.require-once]: failed to open stream: No such file or directory in /var/www/html/omeka-2.2.2/plugins/BagIt/BagItPlugin.php on line 35

Fatal error: require_once() [function.require]: Failed opening required '/var/www/html/omeka-2.2.2/plugins/BagIt/models/Table/Table_BagitFileCollection.php' (include_path='/var/www/html/omeka-2.2.2/application/libraries:/var/www/html/omeka-2.2.2/application/models:.:/usr/share/pear:/usr/share/php:/var/www/html/omeka-2.2.2/plugins/SimplePages/models:/var/www/html/omeka-2.2.2/plugins/ExhibitBuilder/models:/var/www/html/omeka-2.2.2/plugins/ExhibitBuilder/libraries:/var/www/html/omeka-2.2.2/plugins/DublinCoreExtended/models:/var/www/html/omeka-2.2.2/plugins/Geolocation/models:/var/www/html/omeka-2.2.2/plugins/ItemRelations/models:/var/www/html/omeka-2.2.2/plugins/OaiPmhRepository/models:/var/www/html/omeka-2.2.2/plugins/OaiPmhRepository/libraries:/var/www/html/omeka-2.2.2/plugins/Dropbox/models:/var/www/html/omeka-2.2.2/plugins/LcSuggest/models:/var/www/html/omeka-2.2.2/plugins/LcSuggest/libraries:/var/www/html/omeka-2.2.2/plugins/SimpleVocab/models:/var/www/html/omeka-2.2.2/plugins/SimpleVocab/ in /var/www/html/omeka-2.2.2/plugins/BagIt/BagItPlugin.php on line 35

**Comment by alfski** [comment]
Hi, in BagItPlugin.php I commented out the requires for two non-existant php files.

```
require_once BAGIT_PLUGIN_DIRECTORY . '/BagItPlugin.php';
require_once BAGIT_PLUGIN_DIRECTORY . '/helpers/BagItFunctions.php';
require_once BAGIT_PLUGIN_DIRECTORY . '/lib/BagItPHP/lib/bagit.php';
require_once BAGIT_PLUGIN_DIRECTORY . '/models/BagitFileCollection.php';
require_once BAGIT_PLUGIN_DIRECTORY . '/models/BagitFileCollectionAssociation.php';
//Alf require_once BAGIT_PLUGIN_DIRECTORY . '/models/Table/Table_BagitFileCollection.php';
//Alf require_once BAGIT_PLUGIN_DIRECTORY . '/models/Table/Table_BagitFileCollectionAssociation.php';
```

So the plugin will at least load, but I haven't tested it for functionality!

**Comment by alfski** [comment]
Scratch that. For Omeka-2.2.2 grab the BagItPlugin from scholarslab git. I suspect the plugin zip on the Omeka Plugins listing page is incomplete.

https://github.com/scholarslab/BagItPlugin/tree/feature/omeka2-2
